on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: 0 22 * * 0

name: Run FRED Econ Data

jobs:
  refresh-the-dashboard:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4
        with:
          ref: "main"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --execute --to notebook --output FRED-gov-data/output.csv FRED-gov-data/gov-data-FRED-API.ipynb
        env:
          EIA_API_KEY: ${{ secrets.FRED_API_KEY }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_NAME: ${{ secrets.USER_NAME }}
      - name: Commit and push changes
        run: |
          git config --global user.email "${USER_EMAIL}"
          git config --global user.name "${USER_NAME}"
          git add FRED-gov-data/output.csv
          git commit -m "Automated update of FRED econ data"
          git push origin main
