on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: 0 22 * * 0

name: Run FRED Econ Data

jobs:
  refresh-the-dashboard:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set environment variables
        env:
          EIA_API_KEY: ${{ secrets.FRED_API_KEY }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_NAME: ${{ secrets.USER_NAME }}
      - name: Run Notebook
        uses: papermill/execute-notebook@v2
        with:
          input_path: FRED-gov-data/gov-data-FRED-API.ipynb
          output_path: FRED-gov-data/output.csv
      - name: Commit and push changes
        uses: actions/checkout@v4
        run: |
          git config --global user.email "${USER_EMAIL}"
          git config --global user.name "${USER_NAME}"
          git add FRED-gov-data/output.csv
          git commit -m "Automated update of FRED econ data"
          git push origin main
