name: Data Refresh - Python

on:
  push:
    branches: main
  schedule:
    - cron: "0 */12 * * *"
jobs:
  refresh-the-dashboard:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Data Refresh
        run: ./FRED-gov-data/gov-data-FRED-API.ipynb
        env:
          EIA_API_KEY: ${{ secrets.FRED_API_KEY }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_NAME: ${{ secrets.USER_NAME }}
